tartec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app01/', include(('app01.urls', "app01"), namespace='app01')),
    path('', include('web.urls')),
]

web/urls.py
# @Time    : 2023/12/21 10:38
# @Author  : 🍁
# @File    : urls.py
# @Software: PyCharm

from django.urls import path, re_path, include
from web.views import account
from web.views import verify
from web.views import home
from web.views import project
from web.views import statistic
from web.views import wiki
from web.views import file
from web.views import setting
from web.views import issues
from web.views import dashboard
from web.views import price

urlpatterns = [
    # 主页
    path("", home.IndexView.as_view(), name="index"),
    # 注册页面
    path("register/", account.RegisterView.as_view(), name="register"),
    # 发送短信验证码
    re_path(r"^sms/(?P<mobile>1[3-9]\d{9})/$", verify.Send_SMS_view.as_view()),
    # 登录
    path("login/", account.LoginView.as_view(), name="login"),
    # 短信登录
    path("login/sms/", account.LoginSMSView.as_view(), name="login_sms"),
    # 图形验证码
    re_path(r"^image/(?P<uuid>[\w-]+)/$", verify.ImageCodeView.as_view(), name="image_code"),
    # 推出登录
    path("logout/", account.LogoutView.as_view(), name="logout"),
    # 项目管理
    path("project/list/", project.ProjectListView.as_view(), name="project_list"),
    # 星标
    re_path(r"^project/star/(?P<project_type>\w+)/(?P<id>\d+)/$", project.ProjectStarView.as_view(),
            name="project_star"),
    # 取消星标
    re_path(r"^project/unstar/(?P<project_type>\w+)/(?P<id>\d+)/$", project.UnProjectStarView.as_view(),
            name="project_unstar"),

    # 项目管理
    # 使用路由分发的形式
    re_path(r"manage/(?P<project_id>\d+)/", include([
        # 概览
        path("dashboard/", dashboard.DashboardView.as_view(), name="dashboard"),
        path("dashboard/charts/", dashboard.DashboardChartsView.as_view(), name="dashboard_charts"),

        # 问题
        path("issuse/", issues.IssuesView.as_view(), name="issues"),
        # 问题操作页面
        re_path(r"issuse/detail/(?P<issues_id>\d+)/", issues.IssuesDetailView.as_view(), name="issues_detail"),
        # 问题操作记录
        re_path(r"issuse/record/(?P<issues_id>\d+)/", issues.IssuesRecordView.as_view(), name="issues_record"),
        # 操作变更记录
        re_path(r"issuse/change/(?P<issues_id>\d+)/", issues.IssuesChangeRecordView.as_view(), name="issues_change"),
        # 生成邀请码
        path("invite/", issues.InviteView.as_view(), name="invite"),

        # 统计
        path("statistics/", statistic.StatisticsView.as_view(), name="statistic"),
        path("statistics/priority/", statistic.StatisticsPriorityView.as_view(), name="statistics_priority"),
        path("statistics/statistics_project_user/", statistic.StatisticsPriorityUserView.as_view(),
             name="statistics_project_user"),

        # 文件板块
        path("file/", file.FileView.as_view(), name="file"),
        # 文件删除
        path("file/del/", file.DelFile.as_view(), name="del_file"),
        # 前端返回文件 上传到数据库
        path("file/upload/", file.UploadFile.as_view(), name="upload_file"),
        # 获取临时凭证
        path("cos/credential/", file.CosCredential.as_view(), name="cos_credential"),
        # 下载文件
        re_path(r"file/download/(?P<file_id>\d+)/", file.DownloadFileView.as_view(), name="download_file"),

        # wiki板块
        path("wiki/", wiki.WikiView.as_view(), name="wiki"),
        # wiki form
        path("wiki/add/", wiki.AddWikiView.as_view(), name="add_wiki"),
        # wiki 更新
        re_path(r"wiki/update/(?P<update_id>\d+)/", wiki.UpdateWikiView.as_view(), name="update_wiki"),
        # wiki delete
        re_path(r"wiki/delete/(?P<delete_id>\d+)/", wiki.DeleteWikiView.as_view(), name="delete_wiki"),
        # wiki 项目目录
        path("wiki/catalog/", wiki.WikiCatalogView.as_view(), name="wiki_catalog"),
        # wiki 上传图片
        path("wiki/upload/", wiki.WikiUploadView.as_view(), name="wiki_upload"),

        # 设置板块
        path("setting/", setting.SettingView.as_view(), name="setting"),
        # 删除项目
        path("setting/delete/", setting.SettingDeleteView.as_view(), name="delete_project"),
    ])),

    # 邀请码链接
    re_path(r"invite/join/(?P<code>[\w-]+)/", issues.InviteJoin.as_view(), name="invite_join"),

    # 价格
    path("price/", price.PriceView.as_view(), name="price"),
    path("pay/", price.PayView.as_view(), name="pay"),
    path("pay/notify/", price.PayNotifyView.as_view(), name="pay_notify"),
    re_path(r"price/list/(?P<policy_id>\d+)/", price.PriceListView.as_view(), name="payment")
]

web/models.py
from django.db import models


# Create your models here.

# 用户信息表
class User(models.Model):
    """
    用户信息表
    """
    username = models.CharField(max_length=20, verbose_name='用户名', db_index=True)  # db_index=True 在数据库中创建索引，使其查询的更快
    password = models.CharField(max_length=64, verbose_name='密码')
    email = models.EmailField(max_length=50, verbose_name='邮箱')
    mobile = models.CharField(max_length=11, verbose_name='手机号', db_index=True)

    price_classify = models.ForeignKey(verbose_name="价格策略", to="PriceClassify", on_delete=models.CASCADE, null=True,
                                       blank=True, default=1)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user'
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name


# 价格分布表
class PriceClassify(models.Model):
    """ 价格分布表 """
    price_classify = (
        (1, "免费版"),
        (2, "收费版"),
        (3, "其他")
    )
    # SmallIntegerField 小的非负整数
    classify = models.SmallIntegerField(verbose_name="收费类型", choices=price_classify, default=1)
    title = models.CharField(max_length=20, verbose_name="标题")
    # PositiveIntegerField 只能存储正整数值
    price = models.PositiveIntegerField(verbose_name="价格", null=True, blank=True, default=None)

    create_projects = models.PositiveIntegerField(verbose_name="创建项目个数")
    everyone_project_member = models.PositiveIntegerField(verbose_name="每个项目成员个数")
    every_project_space = models.BigIntegerField(verbose_name="每个项目空间", help_text="G")
    project_file_space = models.BigIntegerField(verbose_name="单文件空间", help_text="M")

    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        db_table = "price"
        verbose_name = "价格策略"
        verbose_name_plural = verbose_name


# 用户价格方案
class TransactionRecord(models.Model):
    """ 用户价格方案 """
    state_choice = (
        (1, "已支付"),
        (2, "未支付")
    )
    state = models.SmallIntegerField(verbose_name="支付状态", choices=state_choice, default=2)
    order = models.CharField(verbose_name="订单号", max_length=64, unique=True)
    user = models.ForeignKey(verbose_name="用户", to="User", on_delete=models.CASCADE)

    price_classify = models.ForeignKey(verbose_name="价格策略", to="PriceClassify", on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name="数量(年)", help_text="0表示无限期")
    price = models.PositiveIntegerField(verbose_name="实际支付")

    start_date = models.DateTimeField(verbose_name="开始时间", null=True, blank=True)
    end_date = models.DateTimeField(verbose_name="结束时间", null=True, blank=True)
    create_date = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    class Meta:
        db_table = "transaction"
        verbose_name = "交易记录"
        verbose_name_plural = verbose_name


# 新建项目
class Project(models.Model):
    """ 新建项目 """
    COLOR_CHOICE = (
        (1, "#0000FF"),
        (2, "#BBFFFF"),
        (3, "#FFF0F5"),
        (4, "#708090"),
        (5, "#FF69B4"),
        (6, "#436EEE"),
        (7, "#9C9C9C"),
    )
    project_title = models.CharField(verbose_name="项目名称", max_length=32)
    color = models.SmallIntegerField(verbose_name="颜色", choices=COLOR_CHOICE, default=1)
    description = models.CharField(verbose_name="描述", max_length=255, null=True, blank=True)
    star = models.BooleanField(verbose_name="星标", default=False)
    space_used = models.BigIntegerField(verbose_name="已使用空间", default=0, help_text="字节")

    participant = models.PositiveIntegerField(verbose_name="参与人数", default=1)
    created_by = models.ForeignKey(verbose_name="创建者", to="User", on_delete=models.CASCADE)
    create_date = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)

    bucket = models.CharField(verbose_name="COS桶", max_length=128, null=True, blank=True)
    region = models.CharField(verbose_name="COS桶区域", max_length=32, null=True, blank=True)

    class Meta:
        db_table = "project"
        verbose_name = "项目"
        verbose_name_plural = verbose_name


# 项目参与者
class UserProject(models.Model):
    """ 项目参与者 """
    user = models.ForeignKey(verbose_name="参与者", to="User", related_name="projects", on_delete=models.CASCADE)
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.CASCADE)
    star = models.BooleanField(verbose_name="星标", default=False)
    create_date = models.DateTimeField(verbose_name="加入时间", auto_now_add=True)

    class Meta:
        db_table = "user_project"
        verbose_name = "项目参与者"
        verbose_name_plural = verbose_name


# wiki 管理
class Wiki(models.Model):
    """ wiki """
    project_id = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.CASCADE)
    title = models.CharField(max_length=20, verbose_name="标题")
    content = models.TextField(verbose_name="内容")
    depth = models.SmallIntegerField(verbose_name="标签深度", default=1)

    # related_name="children" 设置反向查询的名字
    parent_id = models.ForeignKey(verbose_name="父ID", to="Wiki", on_delete=models.CASCADE, related_name="children",
                                  default=None, blank=True,
                                  null=True)

    def __str__(self):
        return self.title  # 返回标题作为字符串

    class Meta():
        db_table = "wiki"
        verbose_name = "wiki知识库"
        verbose_name_plural = verbose_name


# 文件
class File(models.Model):
    file_types = (
        (1, "文件"),
        (2, "文件夹")
    )
    project_id = models.ForeignKey(to="Project", on_delete=models.CASCADE, verbose_name="项目ID")
    title = models.CharField(max_length=25, verbose_name="文件名称")
    type = models.SmallIntegerField(verbose_name="文件类型", choices=file_types, default=1)
    size = models.CharField(max_length=64, verbose_name="文件大小", help_text="字节", blank=True, null=True,
                            default=None)
    key = models.CharField(max_length=128, verbose_name="文件key", blank=True, null=True, default=None)
    parent_id = models.ForeignKey(to="self", on_delete=models.CASCADE, related_name="children", verbose_name="父文件",
                                  default=None, blank=True, null=True)
    file_path = models.CharField(max_length=255, verbose_name="文件路径", blank=True, null=True)

    revise = models.ForeignKey(to="User", on_delete=models.SET("-"), related_name="user_id", verbose_name="修改者")
    create_date = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    update_date = models.DateTimeField(verbose_name="修改时间", auto_now=True)

    class Meta():
        db_table = "file"
        verbose_name = "文件管理"
        verbose_name_plural = verbose_name


# 问题
class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType', on_delete=models.CASCADE)
    module = models.ForeignKey(verbose_name='模块', to='Module', on_delete=models.CASCADE, null=True, blank=True)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='User', on_delete=models.CASCADE, related_name='task', null=True,
                               blank=True)
    attention = models.ManyToManyField(verbose_name='关注者', to='User',
                                       related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='User', on_delete=models.CASCADE,
                                related_name='create_problems')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject

    class Meta():
        db_table = "issues"
        verbose_name = "问题"
        verbose_name_plural = verbose_name


class Module(models.Model):
    """ 模块（里程碑）"""
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title

    class Meta():
        db_table = "issues_model"
        verbose_name = "问题模块"
        verbose_name_plural = verbose_name


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """

    PROJECT_INIT_LIST = ["任务", '功能', 'Bug']

    title = models.CharField(verbose_name='类型名称', max_length=32)
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta():
        db_table = "issues_type"
        verbose_name = "问题类型"
        verbose_name_plural = verbose_name


class RecordingModel(models.Model):
    issues = models.ForeignKey(to="Issues", on_delete=models.CASCADE, verbose_name="问题对象")
    action = models.TextField(verbose_name="操作")
    RECORDING_STATUS = (
        (1, "修改记录"),
        (2, "回复")
    )
    status = models.SmallIntegerField(verbose_name="操作状态", choices=RECORDING_STATUS)

web/views/dashboard.py
# @Time    : 2024/3/1 22:23
# @Author  : 🍁
# @File    : dashboard.py
# @Software: PyCharm
import collections
import datetime
import time

from django.views import View
from django import http
from django.shortcuts import render
from django.db.models import Count

from web import models


class DashboardView(View):
    def get(self, request, project_id):
        # 问题的数据处理
        issues_dict = collections.OrderedDict()
        for key, text in models.Issues.status_choices:
            issues_dict[key] = {"text": text, "count": 0}
        # 根据status 进行分组，并以id统计数量
        status_count = models.Issues.objects.filter(project_id=project_id).values("status").annotate(ct=Count("id"))
        for item in status_count:
            issues_dict[item["status"]]["count"] = item["ct"]

        # 项目参与者
        project_join = models.UserProject.objects.filter(project_id=project_id).values("user_id", "user__username")

        # 项目动态
        top_ten = models.Issues.objects.filter(project_id=project_id, assign__isnull=False).order_by("-id")[0:10]
        context = {
            "issues_dict": issues_dict,
            "project_join": project_join,
            "top_ten": top_ten,
        }
        return render(request, "dashboard.html", context)


# 画图
class DashboardChartsView(View):
    def get(self, request, project_id):
        # 拿到今天的日期
        today = datetime.datetime.now().date()
        day_count_dict = {}
        for i in range(0, 30):
            date = today - datetime.timedelta(days=30 - i)
            day_count_dict[str(date)] = [time.mktime(date.timetuple()) * 1000, 0]
        # """
        # create_datetime__gte=today - datetime.timedelta(days=30)
        # 拿到30天之前日期的数据
        #
        # select={"ctime": "strftime(%%Y-%%m-%%d, issues.create_datetime)"} sqlite 语法里面的函数strftime
        # select={"ctime": "DATE_FORMAT(issues.create_datetime, %%Y-%%m-%%d)"} mysql 语法里面的函数DATE_FORMAT
        # trftime(%%Y-%%m-%%d, issues.create_datetime) 查询时间为xx年xx月xx日 的时间，并新建一列查询，列名为ctime
        # select id, name, strftime(%%Y-%%m-%%d, issues.create_datetime) as ctime
        # """
        day_count = models.Issues.objects.filter(project_id=project_id,
                                                 create_datetime__gte=today - datetime.timedelta(days=30)
                                                 ).extra(
            select={"ctime": "DATE_FORMAT(issues.create_datetime, '%%Y-%%m-%%d')"}
        ).values("ctime").annotate(ct=Count("id"))

        for item in day_count:
            day_count_dict[item["ctime"]][1] = item["ct"]
        return http.JsonResponse({"status": True, "data": day_count_dict})

web/templates/index.html
{% extends "layout/basic.html" %}
{% load static %}

{% block title %}
    主页
{% endblock %}

{% block css %}
    <style>
    img{
        width: 100%;
    }
    </style>
{% endblock %}

{% block content %}
    <img src="{% static "image/index/index-1.png" %}" alt="">
    <img src="{% static "image/index/index-2.png" %}" alt="">
    <img src="{% static "image/index/index-3.png" %}" alt="">
    <img src="{% static "image/index/index-4.png" %}" alt="">
{% endblock %}

{% block js %}

{% endblock %}

web/templates/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}加入项目{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-danger no-radius">
                <h4><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ error }}</h4>
            </div>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i> 加入成功 </h4>
                <a href="{% url 'dashboard' project_id=project.id %}">点击跳转至项目</a>
            </div>
        {% endif %}

    </div>

{% endblock %}

web/templates/login.html
{% extends "layout/basic.html" %}
{% load static %}

{% block title %}
    用户登录
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static "css/account.css" %}">
    <style>
        .err_msg {
            height: 30px;
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="app">
        <div class="account">
            <h1 class="title">用户登录</h1>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.label == "图片验证码" %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="clearfix">
                                <div class="col-md-6" style="padding-left: 0">{{ field }}</div>
                                <div class="col-md-6">
                                    <img v-bind:src="image_code_url" alt="" @click="get_image_code">
                                </div>
                            </div>
                            <span v-show="{{ field.name }}_error"
                                  class="err_msg">[[ {{ field.name }}_error_msg ]]</span>
                            {#                展示由后端检验报错的信息#}
                            {% if sms_err_code == 100 %}
                                <div><span class="err_msg">{{ sms_errmsg }}</span></div>
                            {% endif %}
                        </div>

                    {% elif field.label == "uuid" %}
                        <label for="{{ field.id_for_label }}" style="display: none">{{ field.label }}</label>
                        <div style="display: none">{{ field }}</div>
                    {% else %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div>{{ field }}</div>
                            <span v-show="{{ field.name }}_error"
                                  class="err_msg">[[ {{ field.name }}_error_msg ]]</span>
                        </div>
                    {% endif %}
                {% endfor %}
                <div>
                    <span class="err_msg">{{ err_msg }}</span>
                </div>
                <div>
                    <div style="float: right">
                        <a href="{% url "login_sms" %}">忘记密码？</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-3">
                        <button class="btn-primary" type="submit">登录</button>
                    </div>
                </div>


            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "js/vue-3.1.2.js" %}"></script>
    <script src="{% static "js/axios-0.18.0.min.js" %}"></script>
    <script src="{% static "js/common.js" %}"></script>
    <script src="{% static "js/login.js" %}"></script>
{% endblock %}

web/templates/payment.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %} 订单 {% endblock %}

{% block content %}

    <div class="container">
        <h2>订单信息（30分钟失效）</h2>
        <table class="table">
            <thead>
            <tr>
                <th>订单</th>
                <th>单价</th>
                <th>数量</th>
                <th>原价</th>
                <th>原订单抵扣</th>
                <th>实际支付</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ policy_object.title }}</td>
                <td>¥{{ policy_object.price }}</td>
                <td>{{ number }}</td>
                <td>¥{{ origin_price }}</td>
                <td>¥{{ balance }}</td>
                <td>¥{{ price }}</td>
            </tr>
            </tbody>
        </table>
        {% if transaction %}
            <div class="alert alert-warning">
                <div>原订单抵扣：¥{{ balance }}</div>
                <div style="margin-top: 10px">
                    原订单的时间为 {{ transaction.start_date }}
                    ~ {{ transaction.end_date }}，且实际支付¥{{ transaction.price }}
                </div>
            </div>
        {% endif %}
        <a class="btn btn-primary" href="{% url "pay" %}">立即支付</a>
    </div>

{% endblock %}

web/templates/project_list.html
{% extends "layout/manage.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "css/project_list.css" %}">
{% endblock %}

{% block title %}
    项目
{% endblock %}

{% block content %}
    <div class="container-fluid project">
        <a href="" class="btn btn-primary" data-toggle="modal" data-target="#addProject">
            <i class="fa fa-plus-circle" aria-hidden="true"></i> 新建项目</a>
    </div>
    <!-- 添加项目的模态框 -->
    <div class="modal fade" id="addProject" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新 建 项 目</h4>
                </div>
                <div class="modal-body">
                    <form id="addForm">
                        {% for field in form %}
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error_msg"></span>
                            </div>

                        {% endfor %}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="onSubmit" type="button" class="btn btn-primary">确定</button>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i> 星标</div>
        <div class="panel-body">
            {% for item in projects.star %}
                <div class="item">
                    <a href="{% url 'dashboard' project_id=item.value.id %}" class="title"
                       style="background-color: {{ item.value.get_color_display }};">{{ item.value.project_title }}</a>
                    <div class="info">
                        <div>
                            <a href="{% url 'project_unstar' id=item.value.id project_type=item.type %}">
                                <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e"></i>
                            </a>
                            <span>{{ item.value.created_by.username }}</span>
                        </div>
                        <div>
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            <span>{{ item.value.participant }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i> 我创建的项目</div>
        <div class="panel-body">
            {% for item in projects.my %}
                <div class="item">
                    <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                       style="background-color: {{ item.get_color_display }};">{{ item.project_title }}</a>
                    <div class="info">
                        <div>
                            <a href="{% url 'project_star' id=item.id project_type='my' %}">
                                <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5;"></i>
                            </a>
                            <span>{{ item.created_by.username }}</span>
                        </div>
                        <div>
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            <span>{{ item.participant }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的项目</div>
        <div class="panel-body">
            {% for item in projects.join %}
                <div class="item">
                    <a href="{% url 'dashboard' project_id=item.id %}" class="title"
                       style="background-color: {{ item.get_color_display }};">{{ item.project_title }}</a>
                    <div class="info">
                        <div>
                            <a href="{% url 'project_star' id=item.id project_type='join' %}">
                                <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                            </a>
                            <span>{{ item.created_by.username }}</span>
                        </div>
                        <div>
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            <span>{{ item.participant }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        // jQuery函数，绑定一个点击事件到id为onSubmit的元素上
        $(() => {
            bindSubmit()
        })

        // 函数，绑定表单提交事件
        function bindSubmit() {
            // 点击事件，通过Ajax发送POST请求
            $("#onSubmit").click(() => {
                $.ajax({
                    url: "{% url 'project_list' %}", // 请求的URL，用于提交表单数据
                    type: "POST", // 请求方法为POST
                    data: $("#addForm").serialize(), // 提交的表单数据，通过序列化获取
                    dataType: "JSON", // 返回的数据类型为JSON
                    success: function (res) { // 请求成功后的回调函数
                        console.log(res) // 打印返回的数据
                        if (res.status) { // 如果返回的状态为true
                            location.href = location.href // 重新加载当前页面
                            // location.reload() 两个都是刷新一下页面，可以把创建的项目显示到页面
                        } else { // 如果返回的状态为false
                            $.each(res.error, function (key, value) { // 遍历错误信息
                                $("#id_" + key).next().text(value[0]) // 将错误信息展示在对应字段的下一个兄弟元素上
                            })
                        }
                    }
                })
            })
        }

    </script>
{% endblock %}